# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThatSportThings' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    rn_path = '../node_modules/react-native'

    # Pods for ThatSportThings
    
    pod 'Firebase'
    pod 'Firebase/Messaging'
    
    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
    ]
    
    #pod 'RNImageCropPicker', :path =>  '../..'
    target 'ThatSportThingsTests' do
        inherit! :search_paths
        # Pods for testing
    end
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == "React"
                target.remove_from_project
            end
        end
    end
    
end

target 'ThatSportThings-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for ThatSportThings-tvOS
    
    target 'ThatSportThings-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
